#!/usr/bin/env python3
"""Generate docs/llms-full.txt from the repo's substantive documentation.

`docs/llms.txt` is a link map: an answer engine that reads it still has to
fetch seven more URLs to get the actual content. `llms-full.txt` is the
companion convention that inlines that content, so a model absorbs the whole
reference in one request. Both are served from the Pages site root.

Sources are concatenated in reading order with a machine-readable separator
before each, carrying the source path and its canonical URL.

Relative markdown links are rewritten to absolute URLs on the way in. The
bundle is served from the Pages site root, which is the `docs/` directory, so
a relative `PATTERNS.md` written for the repo root would resolve against the
site root and 404. Every target is therefore resolved against its own source
document's directory and pointed at the repo browser, or at the site for the
files the site actually serves.

Usage:
    python scripts/gen_llms_full.py            # write docs/llms-full.txt
    python scripts/gen_llms_full.py --check    # exit 1 if the file is stale
    python scripts/gen_llms_full.py --selftest # assert the link resolver
"""

from __future__ import annotations

import argparse
import posixpath
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "docs" / "llms-full.txt"

BLOB = "https://github.com/jimy-r/agent-workspace-architecture/blob/main/"
SITE = "https://jimy-r.github.io/agent-workspace-architecture/"

# A markdown link target that is not a bare anchor. The target cannot contain a
# closing paren, which no target in the sources does.
LINK = re.compile(r"\]\(([^)#][^)]*)\)")

# Anything carrying a URI scheme (http:, https: and mailto: are the ones that
# occur) or written protocol-relative is already absolute.
ABSOLUTE = re.compile(r"^(?:[A-Za-z][A-Za-z0-9+.\-]*:|//)")

# docs/ is the Pages site root, so a file under it is reachable on the site.
DOCS = "docs/"

# Reading order: what the repo is, why the shape is the way it is, the full
# structural map, how to build one, how a day of using it goes.
SOURCES = [
    "README.md",
    "PATTERNS.md",
    "META_ARCHITECTURE.md",
    "EVALUATION.md",
    "ADOPTION.md",
    "WORKFLOW.md",
]

# The convention's guidance is to stay comfortably inside a single-fetch
# context budget. Fail loudly rather than publish something no model will read.
MAX_BYTES = 500_000

HEADER = f"""# Agent Workspace Architecture — full text

> A redacted reference for building agent workspaces: the roles, routines,
> hooks, memory, and task coordination that turn a coding agent into a system
> you can hand work to. One person's working setup, published with the
> reasoning attached.

This file is the `llms-full.txt` companion to `llms.txt`. It inlines the full
text of the repository's substantive documentation so a language model can read
the whole reference in one request instead of following the link map.

Generated by `scripts/gen_llms_full.py` — edit the source documents, not this
file. Canonical HTML tour: {SITE}
Repository: https://github.com/jimy-r/agent-workspace-architecture

Contents, in reading order:

{chr(10).join(f"{i}. {name}" for i, name in enumerate(SOURCES, 1))}
"""

SEPARATOR = "=" * 78


def resolve_link(target: str, source: str) -> str | None:
    """Absolute URL for one markdown link target, or None to leave it alone.

    `source` is the repo-relative path of the document the link was found in, so
    a `../PATTERNS.md` written inside `teardowns/` lands on the repo root rather
    than on a path that exists nowhere.
    """
    if target.startswith("#") or ABSOLUTE.match(target):
        return None

    path, _, anchor = target.partition("#")
    if not path:
        return None
    suffix = f"#{anchor}" if anchor else ""

    # normpath drops the trailing slash, so record the directory shape first.
    is_dir = path.endswith("/")
    resolved = posixpath.normpath(posixpath.join(posixpath.dirname(source), path))
    if resolved == "." or resolved == ".." or resolved.startswith("../"):
        # The repo root itself, or a path escaping the repo. Neither has an
        # honest absolute form; leaving it untouched beats inventing one.
        return None

    # A directory is not served by the site at all, so it stays on the repo
    # browser even under docs/. GitHub redirects a blob URL for a directory.
    if is_dir:
        return f"{BLOB}{resolved}{suffix}"

    if resolved == DOCS.rstrip("/"):
        return f"{SITE}{suffix}"
    if resolved.startswith(DOCS):
        return f"{SITE}{resolved[len(DOCS) :]}{suffix}"
    return f"{BLOB}{resolved}{suffix}"


def rewrite_links(text: str, source: str) -> str:
    """Point every relative markdown link in `text` at an absolute URL."""

    def replace(match: re.Match[str]) -> str:
        url = resolve_link(match.group(1), source)
        return match.group(0) if url is None else f"]({url})"

    return LINK.sub(replace, text)


def build() -> str:
    parts = [HEADER]
    for name in SOURCES:
        path = REPO / name
        if not path.exists():
            raise SystemExit(f"ERROR: source document not found: {name}")
        text = rewrite_links(path.read_text(encoding="utf-8").strip(), name)
        parts.append(
            f"\n\n{SEPARATOR}\n"
            f"SOURCE: {name}\n"
            f"URL: {BLOB}{name}\n"
            f"{SEPARATOR}\n\n"
            f"{text}\n"
        )
    return "".join(parts)


def run_self_test() -> int:
    """Assert the link resolver on the shapes the sources actually contain."""
    cases = [
        # (target, source document, expected URL or None to leave alone)
        ("PATTERNS.md", "README.md", f"{BLOB}PATTERNS.md"),
        ("../PATTERNS.md", "teardowns/2026-08-28-herdr.md", f"{BLOB}PATTERNS.md"),
        ("docs/history.md", "README.md", f"{SITE}history.md"),
        ("PATTERNS.md#pattern-16", "README.md", f"{BLOB}PATTERNS.md#pattern-16"),
        ("samples/tasks/", "README.md", f"{BLOB}samples/tasks"),
        ("https://example.com/x.md", "README.md", None),
        ("mailto:someone@example.com", "README.md", None),
    ]
    failures = []
    for target, source, expected in cases:
        actual = resolve_link(target, source)
        if actual != expected:
            failures.append(f"  {target!r} in {source!r}: {actual!r} != {expected!r}")

    # The rewrite must leave everything except the target untouched, including
    # the nested-image link shape the README opens with.
    nested = "[![map](docs/assets/m.png)](https://example.com/tour)"
    rewritten = rewrite_links(nested, "README.md")
    expected_nested = f"[![map]({SITE}assets/m.png)](https://example.com/tour)"
    if rewritten != expected_nested:
        failures.append(f"  nested image link: {rewritten!r} != {expected_nested!r}")

    if failures:
        print("self-test: FAIL", file=sys.stderr)
        print("\n".join(failures), file=sys.stderr)
        return 1
    print(f"self-test: PASS ({len(cases) + 1} link-resolver checks).")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file matches the sources; do not write",
    )
    parser.add_argument(
        "--selftest",
        action="store_true",
        help="assert the link resolver against fixed cases; do not write",
    )
    args = parser.parse_args()

    if args.selftest:
        return run_self_test()

    content = build()
    size = len(content.encode("utf-8"))
    if size > MAX_BYTES:
        print(
            f"ERROR: {size:,} bytes exceeds the {MAX_BYTES:,}-byte budget. "
            "Trim the source list before regenerating.",
            file=sys.stderr,
        )
        return 2

    if args.check:
        if not OUTPUT.exists():
            print("STALE: docs/llms-full.txt does not exist.", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != content:
            print(
                "STALE: docs/llms-full.txt is out of date with its sources. "
                "Run: python scripts/gen_llms_full.py",
                file=sys.stderr,
            )
            return 1
        print(f"docs/llms-full.txt is current ({size:,} bytes).")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO)} ({size:,} bytes, {len(SOURCES)} sources).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
