#!/usr/bin/env python3
"""Generate docs/llms-full.txt from the repo's substantive documentation.

`docs/llms.txt` is a link map: an answer engine that reads it still has to
fetch seven more URLs to get the actual content. `llms-full.txt` is the
companion convention that inlines that content, so a model absorbs the whole
reference in one request. Both are served from the Pages site root.

Sources are concatenated in reading order with a machine-readable separator
before each, carrying the source path and its canonical URL, so relative
markdown links inside a section can still be resolved.

Usage:
    python scripts/gen_llms_full.py            # write docs/llms-full.txt
    python scripts/gen_llms_full.py --check    # exit 1 if the file is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "docs" / "llms-full.txt"

BLOB = "https://github.com/jimy-r/agent-workspace-architecture/blob/main/"
SITE = "https://jimy-r.github.io/agent-workspace-architecture/"

# Reading order: what the repo is, why the shape is the way it is, the full
# structural map, how to build one, how a day of using it goes.
SOURCES = [
    "README.md",
    "PATTERNS.md",
    "META_ARCHITECTURE.md",
    "ADOPTION.md",
    "WORKFLOW.md",
]

# The convention's guidance is to stay comfortably inside a single-fetch
# context budget. Fail loudly rather than publish something no model will read.
MAX_BYTES = 500_000

HEADER = f"""# Agent Workspace Architecture — full text

> A redacted reference for building agent workspaces: the roles, routines,
> hooks, memory, and task coordination that turn a coding agent into a system
> you can hand work to. One person's working setup, published with the
> reasoning attached.

This file is the `llms-full.txt` companion to `llms.txt`. It inlines the full
text of the repository's substantive documentation so a language model can read
the whole reference in one request instead of following the link map.

Generated by `scripts/gen_llms_full.py` — edit the source documents, not this
file. Canonical HTML tour: {SITE}
Repository: https://github.com/jimy-r/agent-workspace-architecture

Contents, in reading order:

{chr(10).join(f"{i}. {name}" for i, name in enumerate(SOURCES, 1))}
"""

SEPARATOR = "=" * 78


def build() -> str:
    parts = [HEADER]
    for name in SOURCES:
        path = REPO / name
        if not path.exists():
            raise SystemExit(f"ERROR: source document not found: {name}")
        text = path.read_text(encoding="utf-8").strip()
        parts.append(
            f"\n\n{SEPARATOR}\n"
            f"SOURCE: {name}\n"
            f"URL: {BLOB}{name}\n"
            f"{SEPARATOR}\n\n"
            f"{text}\n"
        )
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed file matches the sources; do not write",
    )
    args = parser.parse_args()

    content = build()
    size = len(content.encode("utf-8"))
    if size > MAX_BYTES:
        print(
            f"ERROR: {size:,} bytes exceeds the {MAX_BYTES:,}-byte budget. "
            "Trim the source list before regenerating.",
            file=sys.stderr,
        )
        return 2

    if args.check:
        if not OUTPUT.exists():
            print("STALE: docs/llms-full.txt does not exist.", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != content:
            print(
                "STALE: docs/llms-full.txt is out of date with its sources. "
                "Run: python scripts/gen_llms_full.py",
                file=sys.stderr,
            )
            return 1
        print(f"docs/llms-full.txt is current ({size:,} bytes).")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO)} ({size:,} bytes, {len(SOURCES)} sources).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
